package main

import "feedserver/internal/model"

// SeedCatalog contains all 127 feed sources ported from FEED_CATALOG in core-views.js.
var SeedCatalog = []model.Source{
	// Research & Science
	{Key: "arxiv", Name: "arXiv", Desc: "Latest CS research papers", Cat: "Research & Science", Special: "arxiv", Favicon: "arxiv.org"},
	{Key: "nature", Name: "Nature", Desc: "Scientific research and discoveries", Cat: "Research & Science", URL: "https://www.nature.com/nature.rss", Favicon: "nature.com"},
	{Key: "science", Name: "Science", Desc: "Peer-reviewed research from AAAS", Cat: "Research & Science", URL: "https://www.science.org/rss/news_current.xml", Favicon: "science.org"},
	{Key: "quanta", Name: "Quanta Magazine", Desc: "In-depth math and science journalism", Cat: "Research & Science", URL: "https://www.quantamagazine.org/feed/", Favicon: "quantamagazine.org"},
	{Key: "sciamerican", Name: "Scientific American", Desc: "Science news and features", Cat: "Research & Science", URL: "http://rss.sciam.com/ScientificAmerican-Global", Favicon: "scientificamerican.com"},
	{Key: "newscientist", Name: "New Scientist", Desc: "Science and technology news", Cat: "Research & Science", URL: "https://www.newscientist.com/section/news/feed/", Favicon: "newscientist.com"},
	{Key: "phys", Name: "Phys.org", Desc: "Physics, space, and earth science", Cat: "Research & Science", URL: "https://phys.org/rss-feed/", Favicon: "phys.org"},

	// Tech & News
	{Key: "hn", Name: "Hacker News", Desc: "Top stories from the tech community", Cat: "Tech & News", Special: "hn", Favicon: "news.ycombinator.com"},
	{Key: "verge", Name: "The Verge", Desc: "Technology news and culture", Cat: "Tech & News", URL: "https://www.theverge.com/rss/index.xml", Favicon: "theverge.com"},
	{Key: "arstechnica", Name: "Ars Technica", Desc: "In-depth technology reporting", Cat: "Tech & News", URL: "https://feeds.arstechnica.com/arstechnica/index", Favicon: "arstechnica.com"},
	{Key: "techcrunch", Name: "TechCrunch", Desc: "Startup and technology news", Cat: "Tech & News", URL: "https://techcrunch.com/feed/", Favicon: "techcrunch.com"},
	{Key: "wired", Name: "Wired", Desc: "Future trends in tech and culture", Cat: "Tech & News", URL: "https://www.wired.com/feed/rss", Favicon: "wired.com"},
	{Key: "mittr", Name: "MIT Tech Review", Desc: "Emerging technology analysis", Cat: "Tech & News", URL: "https://www.technologyreview.com/feed/", Favicon: "technologyreview.com"},

	// Programming
	{Key: "lobsters", Name: "Lobsters", Desc: "Community-curated programming links", Cat: "Programming", URL: "https://lobste.rs/rss", Favicon: "lobste.rs"},
	{Key: "devto", Name: "DEV Community", Desc: "Developer articles and tutorials", Cat: "Programming", URL: "https://dev.to/feed", Favicon: "dev.to"},
	{Key: "hackernoon", Name: "Hacker Noon", Desc: "Tech industry stories and takes", Cat: "Programming", URL: "https://hackernoon.com/feed", Favicon: "hackernoon.com"},
	{Key: "smashing", Name: "Smashing Magazine", Desc: "Web design and development", Cat: "Programming", URL: "https://www.smashingmagazine.com/feed/", Favicon: "smashingmagazine.com"},
	{Key: "github", Name: "GitHub Blog", Desc: "Developer platform news and features", Cat: "Programming", URL: "https://github.blog/feed/", Favicon: "github.com"},
	{Key: "stackoverflow", Name: "Stack Overflow Blog", Desc: "Programming Q&A and developer insights", Cat: "Programming", URL: "https://stackoverflow.blog/feed/", Favicon: "stackoverflow.com"},
	{Key: "reddit-programming", Name: "r/programming", Desc: "Programming subreddit discussions", Cat: "Programming", URL: "https://www.reddit.com/r/programming/.rss", Favicon: "reddit.com"},
	{Key: "medium-engineering", Name: "Medium Engineering", Desc: "Engineering blog from Medium", Cat: "Programming", URL: "https://medium.engineering/feed", Favicon: "medium.com"},
	{Key: "chromium", Name: "Chromium Blog", Desc: "Chrome and Chromium development", Cat: "Programming", URL: "https://blog.chromium.org/feeds/posts/default", Favicon: "blog.chromium.org"},
	{Key: "android-developers", Name: "Android Developers", Desc: "Official Android development blog", Cat: "Programming", URL: "https://android-developers.googleblog.com/feeds/posts/default", Favicon: "developer.android.com"},

	// AI & Machine Learning
	{Key: "gradient", Name: "The Gradient", Desc: "AI research perspectives", Cat: "AI & Machine Learning", URL: "https://thegradient.pub/rss/", Favicon: "thegradient.pub"},
	{Key: "nvidia-blog", Name: "NVIDIA Blog", Desc: "AI, GPUs, and deep learning updates", Cat: "AI & Machine Learning", URL: "https://blogs.nvidia.com/feed/", Favicon: "nvidia.com"},
	{Key: "openai-blog", Name: "OpenAI", Desc: "AI research and product announcements", Cat: "AI & Machine Learning", URL: "https://openai.com/news/rss.xml", Favicon: "openai.com"},
	{Key: "anthropic-blog", Name: "Anthropic", Desc: "AI safety research and updates", Cat: "AI & Machine Learning", URL: "https://www.anthropic.com/rss/news.xml", Favicon: "anthropic.com"},
	{Key: "meta-engineering", Name: "Engineering at Meta", Desc: "AI infrastructure and engineering", Cat: "AI & Machine Learning", URL: "https://engineering.fb.com/feed/", Favicon: "engineering.fb.com"},
	{Key: "aiweirdness", Name: "AI Weirdness", Desc: "Humor and oddities in AI", Cat: "AI & Machine Learning", URL: "https://www.aiweirdness.com/rss/", Favicon: "aiweirdness.com"},
	{Key: "mlmastery", Name: "ML Mastery", Desc: "Machine learning tutorials and guides", Cat: "AI & Machine Learning", URL: "https://machinelearningmastery.com/feed/", Favicon: "machinelearningmastery.com"},
	{Key: "reddit-machinelearning", Name: "r/MachineLearning", Desc: "ML research and discussions", Cat: "AI & Machine Learning", URL: "https://www.reddit.com/r/MachineLearning/.rss", Favicon: "reddit.com"},

	// Security
	{Key: "krebs", Name: "Krebs on Security", Desc: "Cybersecurity news and investigations", Cat: "Security", URL: "https://krebsonsecurity.com/feed/", Favicon: "krebsonsecurity.com"},

	// Ideas & Culture
	{Key: "aeon", Name: "Aeon", Desc: "Essays on science, philosophy, society", Cat: "Ideas & Culture", URL: "https://aeon.co/feed", Favicon: "aeon.co"},
	{Key: "nautilus", Name: "Nautilus", Desc: "Science meets philosophy and culture", Cat: "Ideas & Culture", URL: "https://nautil.us/feed/", Favicon: "nautil.us"},
	{Key: "atlantic", Name: "The Atlantic", Desc: "Politics, culture, and ideas", Cat: "Ideas & Culture", URL: "https://www.theatlantic.com/feed/all/", Favicon: "theatlantic.com"},
	{Key: "newyorker", Name: "The New Yorker", Desc: "Reporting, commentary, and essays", Cat: "Ideas & Culture", URL: "https://www.newyorker.com/feed/everything", Favicon: "newyorker.com"},
	{Key: "brainpickings", Name: "The Marginalian", Desc: "Literature, science, and philosophy", Cat: "Ideas & Culture", URL: "https://www.themarginalian.org/feed/", Favicon: "themarginalian.org"},

	// Sports
	{Key: "espn", Name: "ESPN", Desc: "Top sports news and scores", Cat: "Sports", URL: "https://www.espn.com/espn/rss/news", Favicon: "espn.com"},
	{Key: "theathletic", Name: "The Athletic", Desc: "In-depth sports journalism", Cat: "Sports", URL: "https://theathletic.com/feed/", Favicon: "theathletic.com"},
	{Key: "bleacherreport", Name: "Bleacher Report", Desc: "Sports highlights and analysis", Cat: "Sports", URL: "https://bleacherreport.com/articles/feed", Favicon: "bleacherreport.com"},

	// Prediction Markets
	{Key: "polymarket", Name: "Polymarket", Desc: "Breaking prediction markets", Cat: "Prediction Markets", Special: "polymarket", Favicon: "polymarket.com"},

	// News & World
	{Key: "reuters", Name: "Reuters", Desc: "Breaking world news", Cat: "News & World", URL: "https://feeds.reuters.com/reuters/topNews", Favicon: "reuters.com"},
	{Key: "bbc", Name: "BBC News", Desc: "Global news coverage", Cat: "News & World", URL: "https://feeds.bbci.co.uk/news/rss.xml", Favicon: "bbc.com"},
	{Key: "npr", Name: "NPR", Desc: "National and international news", Cat: "News & World", URL: "https://feeds.npr.org/1001/rss.xml", Favicon: "npr.org"},
	{Key: "apnews", Name: "AP News", Desc: "Breaking news from the Associated Press", Cat: "News & World", URL: "https://rsshub.app/apnews/topics/apf-topnews", Favicon: "apnews.com"},

	// Design
	{Key: "designernews", Name: "Designer News", Desc: "Design community links", Cat: "Design", URL: "https://www.designernews.co/?format=rss", Favicon: "designernews.co"},
	{Key: "sidebar", Name: "Sidebar", Desc: "Five curated design links daily", Cat: "Design", URL: "https://sidebar.io/feed.xml", Favicon: "sidebar.io"},

	// Finance & Economics
	{Key: "ft", Name: "Financial Times", Desc: "Global business and finance", Cat: "Finance & Economics", URL: "https://www.ft.com/rss/home", Favicon: "ft.com"},
	{Key: "economist", Name: "The Economist", Desc: "Global economics and policy", Cat: "Finance & Economics", URL: "https://www.economist.com/latest/rss.xml", Favicon: "economist.com"},
	{Key: "mattstoller", Name: "BIG by Matt Stoller", Desc: "Monopoly power and political economy", Cat: "Finance & Economics", URL: "https://www.thebignewsletter.com/feed", Favicon: "thebignewsletter.com"},

	// Space
	{Key: "nasabreaking", Name: "NASA", Desc: "Space news and mission updates", Cat: "Space", URL: "https://www.nasa.gov/news-release/feed/", Favicon: "nasa.gov"},
	{Key: "spacenews", Name: "SpaceNews", Desc: "Space industry coverage", Cat: "Space", URL: "https://spacenews.com/feed/", Favicon: "spacenews.com"},

	// Blogs & Newsletters
	{Key: "acx", Name: "Astral Codex Ten", Desc: "Scott Alexander on science, philosophy, and rationality", Cat: "Blogs & Newsletters", URL: "https://www.astralcodexten.com/feed", Favicon: "astralcodexten.com"},
	{Key: "dwarkesh", Name: "Dwarkesh Patel", Desc: "Deep-dive interviews on progress and ideas", Cat: "Blogs & Newsletters", URL: "https://www.dwarkesh.com/feed", Favicon: "dwarkesh.com"},
	{Key: "geohot", Name: "geohot", Desc: "George Hotz on technology, AI, and hacking", Cat: "Blogs & Newsletters", URL: "https://geohot.github.io/blog/feed.xml", Favicon: "geohot.github.io"},
	{Key: "lilianweng", Name: "Lil'Log", Desc: "Lilian Weng on deep learning and AI research", Cat: "Blogs & Newsletters", URL: "https://lilianweng.github.io/index.xml", Favicon: "lilianweng.github.io"},
	{Key: "colah", Name: "colah's blog", Desc: "Visual explanations of neural networks", Cat: "Blogs & Newsletters", URL: "https://colah.github.io/rss.xml", Favicon: "colah.github.io"},
	{Key: "dennybritz", Name: "Denny Britz", Desc: "Machine learning and software engineering", Cat: "Blogs & Newsletters", URL: "https://dennybritz.com/index.xml", Favicon: "dennybritz.com"},
	{Key: "gwern", Name: "Gwern", Desc: "Essays on AI, statistics, and technology", Cat: "Blogs & Newsletters", URL: "https://gwern.substack.com/feed", Favicon: "gwern.net"},
	{Key: "lesswrong", Name: "LessWrong", Desc: "Rationality, AI safety, and decision-making", Cat: "Blogs & Newsletters", URL: "https://www.lesswrong.com/feed.xml", Favicon: "lesswrong.com"},
	{Key: "trentonbricken", Name: "Trenton Bricken", Desc: "Computational neuroscience and AI research", Cat: "Blogs & Newsletters", URL: "https://www.trentonbricken.com/feed.xml", Favicon: "trentonbricken.com"},
	{Key: "jasonwei", Name: "Jason Wei", Desc: "Chain-of-thought and LLM research", Cat: "Blogs & Newsletters", URL: "https://www.jasonwei.net/blog?format=rss", Favicon: "jasonwei.net"},
	{Key: "fanpu", Name: "Fan Pu Zeng", Desc: "CS, math, and research", Cat: "Blogs & Newsletters", URL: "https://fanpu.io/feed.xml", Favicon: "fanpu.io"},
	{Key: "mcyoung", Name: "mcyoung", Desc: "Compilers, performance, and systems programming", Cat: "Blogs & Newsletters", URL: "https://mcyoung.xyz/feed.xml", Favicon: "mcyoung.xyz"},
	{Key: "itcanthink", Name: "It Can Think!", Desc: "Substack on AI and cognition", Cat: "Blogs & Newsletters", URL: "https://itcanthink.substack.com/feed", Favicon: "itcanthink.substack.com"},
	{Key: "sanderai", Name: "Sander Dieleman", Desc: "Generative modeling and diffusion models", Cat: "Blogs & Newsletters", URL: "https://sander.ai/feed.xml", Favicon: "sander.ai"},
	{Key: "gundersen", Name: "Gregory Gundersen", Desc: "Statistics, ML, and technical writing", Cat: "Blogs & Newsletters", URL: "https://gregorygundersen.com/feed.xml", Favicon: "gregorygundersen.com"},
	{Key: "brandinho", Name: "Brandinho", Desc: "Data science and machine learning", Cat: "Blogs & Newsletters", URL: "https://brandinho.github.io/feed.xml", Favicon: "brandinho.github.io"},
	{Key: "fabiensanglard", Name: "Fabien Sanglard", Desc: "Game engines, graphics, and systems", Cat: "Blogs & Newsletters", URL: "https://fabiensanglard.net/rss.xml", Favicon: "fabiensanglard.net"},
	{Key: "andyjones", Name: "Andy Jones", Desc: "Statistics, ML, and academic life", Cat: "Blogs & Newsletters", URL: "https://andrewcharlesjones.github.io/feed.xml", Favicon: "andrewcharlesjones.github.io"},
	{Key: "thegeeko", Name: "thegeeko", Desc: "GPU debugging, rendering, and WebSockets", Cat: "Blogs & Newsletters", URL: "https://thegeeko.me/rss.xml", Favicon: "thegeeko.me"},
	{Key: "rohany", Name: "Rohan Yadav", Desc: "Compilers and high-performance computing", Cat: "Blogs & Newsletters", URL: "https://rohany.github.io/index.xml", Favicon: "rohany.github.io"},
	{Key: "eliben", Name: "Eli Bendersky", Desc: "Go, Python, compilers, and ML", Cat: "Blogs & Newsletters", URL: "https://eli.thegreenplace.net/feeds/all.atom.xml", Favicon: "eli.thegreenplace.net"},
	{Key: "jaredtumiel", Name: "Jared Tumiel", Desc: "Physics, computation, and AI", Cat: "Blogs & Newsletters", URL: "https://jaredtumiel.github.io/blog/feed.xml", Favicon: "jaredtumiel.github.io"},
	{Key: "paulcavallaro", Name: "Paul Cavallaro", Desc: "CS, systems, and software engineering", Cat: "Blogs & Newsletters", URL: "https://paulcavallaro.com/blog/index.xml", Favicon: "paulcavallaro.com"},
	{Key: "clashluke", Name: "Lucas Nestler", Desc: "ML normalization, attention, and AI research", Cat: "Blogs & Newsletters", URL: "https://clashluke.github.io/index.xml", Favicon: "clashluke.github.io"},
	{Key: "karpathy", Name: "Andrej Karpathy", Desc: "AI, LLMs, and technical deep dives", Cat: "Blogs & Newsletters", URL: "https://karpathy.bearblog.dev/feed/", Favicon: "karpathy.bearblog.dev"},
	{Key: "wzml", Name: "Hill Climbing", Desc: "Machine learning concepts and techniques", Cat: "Blogs & Newsletters", URL: "https://blog.wz-ml.com/feed.xml", Favicon: "blog.wz-ml.com"},
	{Key: "simonwillison", Name: "Simon Willison", Desc: "Python, Django, AI tools, and LLMs", Cat: "Blogs & Newsletters", URL: "https://simonwillison.net/atom/everything/", Favicon: "simonwillison.net"},
	{Key: "jeffgeerling", Name: "Jeff Geerling", Desc: "Raspberry Pi, Ansible, and open-source hardware", Cat: "Blogs & Newsletters", URL: "https://www.jeffgeerling.com/blog.xml", Favicon: "jeffgeerling.com"},
	{Key: "robotsinplainenglish", Name: "Robots In Plain English", Desc: "Robotics, engineering, and automation", Cat: "Blogs & Newsletters", URL: "https://robotsinplainenglish.substack.com/feed", Favicon: "robotsinplainenglish.com"},
	{Key: "occasionalinformationist", Name: "The Occasional Informationist", Desc: "Information science and related topics", Cat: "Blogs & Newsletters", URL: "https://theoccasionalinformationist.com/feed/", Favicon: "theoccasionalinformationist.com"},
	{Key: "bactra", Name: "Cosma Shalizi", Desc: "Statistics, complexity, and social science", Cat: "Blogs & Newsletters", URL: "http://bactra.org/weblog/index.rss", Favicon: "bactra.org"},
	{Key: "nearblog", Name: "near.blog", Desc: "AI, animals, philosophy, and reflections", Cat: "Blogs & Newsletters", URL: "https://near.blog/feed/", Favicon: "near.blog"},
	{Key: "moultano", Name: "Ryan Moulton", Desc: "ML, game dev, and miscellaneous topics", Cat: "Blogs & Newsletters", URL: "https://moultano.wordpress.com/feed/", Favicon: "moultano.wordpress.com"},
	{Key: "convergentthinking", Name: "Convergent Thinking", Desc: "ML research and deep learning", Cat: "Blogs & Newsletters", URL: "https://convergentthinking.sh/index.xml", Favicon: "convergentthinking.sh"},
	{Key: "entropicthoughts", Name: "Entropic Thoughts", Desc: "Programming and software engineering", Cat: "Blogs & Newsletters", URL: "https://entropicthoughts.com/feed.xml", Favicon: "entropicthoughts.com"},

	// HN Top Blogs 2025
	{Key: "seangoedecke", Name: "Sean Goedecke", Desc: "Software engineering and career", Cat: "HN Top Blogs 2025", URL: "https://www.seangoedecke.com/rss.xml", Favicon: "seangoedecke.com"},
	{Key: "daringfireball", Name: "Daring Fireball", Desc: "Apple, tech, and culture by John Gruber", Cat: "HN Top Blogs 2025", URL: "https://daringfireball.net/feeds/main", Favicon: "daringfireball.net"},
	{Key: "ericmigi", Name: "Eric Migicovsky", Desc: "Hardware, startups, and Pebble", Cat: "HN Top Blogs 2025", URL: "https://ericmigi.com/rss.xml", Favicon: "ericmigi.com"},
	{Key: "antirez", Name: "antirez", Desc: "Redis creator on programming and systems", Cat: "HN Top Blogs 2025", URL: "http://antirez.com/rss", Favicon: "antirez.com"},
	{Key: "idiallo", Name: "Ibrahim Diallo", Desc: "Web development and programming stories", Cat: "HN Top Blogs 2025", URL: "https://idiallo.com/feed.rss", Favicon: "idiallo.com"},
	{Key: "maurycyz", Name: "Maurycy Zarzycki", Desc: "Programming and tech", Cat: "HN Top Blogs 2025", URL: "https://maurycyz.com/index.xml", Favicon: "maurycyz.com"},
	{Key: "pluralistic", Name: "Pluralistic", Desc: "Cory Doctorow on tech, monopolies, and rights", Cat: "HN Top Blogs 2025", URL: "https://pluralistic.net/feed/", Favicon: "pluralistic.net"},
	{Key: "shkspr", Name: "Terence Eden", Desc: "Web standards, tech, and open source", Cat: "HN Top Blogs 2025", URL: "https://shkspr.mobi/blog/feed/", Favicon: "shkspr.mobi"},
	{Key: "lcamtuf", Name: "lcamtuf", Desc: "Security research and fuzzing", Cat: "HN Top Blogs 2025", URL: "https://lcamtuf.substack.com/feed", Favicon: "lcamtuf.substack.com"},
	{Key: "mitchellh", Name: "Mitchell Hashimoto", Desc: "Ghostty, systems, and open source", Cat: "HN Top Blogs 2025", URL: "https://mitchellh.com/feed.xml", Favicon: "mitchellh.com"},
	{Key: "dynomight", Name: "Dynomight", Desc: "Science, data, and contrarian analysis", Cat: "HN Top Blogs 2025", URL: "https://dynomight.net/feed.xml", Favicon: "dynomight.net"},
	{Key: "cks", Name: "Chris Siebenmann", Desc: "Unix, sysadmin, and systems", Cat: "HN Top Blogs 2025", URL: "https://utcc.utoronto.ca/~cks/space/blog/?atom", Favicon: "utcc.utoronto.ca"},
	{Key: "xeiaso", Name: "Xe Iaso", Desc: "Nix, Go, and philosophy of tech", Cat: "HN Top Blogs 2025", URL: "https://xeiaso.net/blog.rss", Favicon: "xeiaso.net"},
	{Key: "oldnewthing", Name: "The Old New Thing", Desc: "Raymond Chen on Windows internals", Cat: "HN Top Blogs 2025", URL: "https://devblogs.microsoft.com/oldnewthing/feed", Favicon: "devblogs.microsoft.com"},
	{Key: "righto", Name: "Ken Shirriff", Desc: "Reverse engineering chips and hardware", Cat: "HN Top Blogs 2025", URL: "https://www.righto.com/feeds/posts/default", Favicon: "righto.com"},
	{Key: "lucumr", Name: "Armin Ronacher", Desc: "Python, Rust, and developer tooling", Cat: "HN Top Blogs 2025", URL: "https://lucumr.pocoo.org/feed.atom", Favicon: "lucumr.pocoo.org"},
	{Key: "skyfall", Name: "Skyfall", Desc: "Tech and engineering", Cat: "HN Top Blogs 2025", URL: "https://skyfall.dev/rss.xml", Favicon: "skyfall.dev"},
	{Key: "garymarcus", Name: "Gary Marcus", Desc: "AI criticism and cognitive science", Cat: "HN Top Blogs 2025", URL: "https://garymarcus.substack.com/feed", Favicon: "garymarcus.substack.com"},
	{Key: "rachelbythebay", Name: "rachelbythebay", Desc: "Systems programming war stories", Cat: "HN Top Blogs 2025", URL: "https://rachelbythebay.com/w/atom.xml", Favicon: "rachelbythebay.com"},
	{Key: "overreacted", Name: "Overreacted", Desc: "Dan Abramov on React and programming", Cat: "HN Top Blogs 2025", URL: "https://overreacted.io/rss.xml", Favicon: "overreacted.io"},
	{Key: "timsh", Name: "Tim Shedor", Desc: "Tech and engineering", Cat: "HN Top Blogs 2025", URL: "https://timsh.org/rss/", Favicon: "timsh.org"},
	{Key: "johndcook", Name: "John D. Cook", Desc: "Math, statistics, and computing", Cat: "HN Top Blogs 2025", URL: "https://www.johndcook.com/blog/feed/", Favicon: "johndcook.com"},
	{Key: "gilesthomas", Name: "Giles Thomas", Desc: "Programming and tech", Cat: "HN Top Blogs 2025", URL: "https://gilesthomas.com/feed/rss.xml", Favicon: "gilesthomas.com"},
	{Key: "matklad", Name: "matklad", Desc: "Rust, rust-analyzer, and IDE tooling", Cat: "HN Top Blogs 2025", URL: "https://matklad.github.io/feed.xml", Favicon: "matklad.github.io"},
	{Key: "derekthompson", Name: "Derek Thompson", Desc: "Culture, economics, and ideas", Cat: "HN Top Blogs 2025", URL: "https://www.theatlantic.com/feed/author/derek-thompson/", Favicon: "theatlantic.com"},
	{Key: "evanhahn", Name: "Evan Hahn", Desc: "Web development and JavaScript", Cat: "HN Top Blogs 2025", URL: "https://evanhahn.com/feed.xml", Favicon: "evanhahn.com"},
	{Key: "terriblesoftware", Name: "Terrible Software", Desc: "Software engineering opinions", Cat: "HN Top Blogs 2025", URL: "https://terriblesoftware.org/feed/", Favicon: "terriblesoftware.org"},
	{Key: "rakhim", Name: "Rakhim", Desc: "Programming and creativity", Cat: "HN Top Blogs 2025", URL: "https://rakhim.exotext.com/rss.xml", Favicon: "rakhim.exotext.com"},
	{Key: "joanwestenberg", Name: "Joan Westenberg", Desc: "Tech culture and criticism", Cat: "HN Top Blogs 2025", URL: "https://joanwestenberg.com/rss", Favicon: "joanwestenberg.com"},
	{Key: "xania", Name: "Matt Godbolt", Desc: "Compilers, C++, and Compiler Explorer", Cat: "HN Top Blogs 2025", URL: "https://xania.org/feed", Favicon: "xania.org"},
	{Key: "micahflee", Name: "Micah Lee", Desc: "Security, privacy, and journalism", Cat: "HN Top Blogs 2025", URL: "https://micahflee.com/feed/", Favicon: "micahflee.com"},
	{Key: "nesbitt", Name: "Andrew Nesbitt", Desc: "Open source and software supply chain", Cat: "HN Top Blogs 2025", URL: "https://nesbitt.io/feed.xml", Favicon: "nesbitt.io"},
	{Key: "constructionphysics", Name: "Construction Physics", Desc: "Engineering, building, and infrastructure", Cat: "HN Top Blogs 2025", URL: "https://www.construction-physics.com/feed", Favicon: "construction-physics.com"},
	{Key: "tedium", Name: "Tedium", Desc: "The dull side of the internet", Cat: "HN Top Blogs 2025", URL: "https://feed.tedium.co/", Favicon: "tedium.co"},
	{Key: "susam", Name: "Susam Pal", Desc: "Math, programming, and Unix", Cat: "HN Top Blogs 2025", URL: "https://susam.net/feed.xml", Favicon: "susam.net"},
	{Key: "hillelwayne", Name: "Hillel Wayne", Desc: "Formal methods and software engineering", Cat: "HN Top Blogs 2025", URL: "https://buttondown.com/hillelwayne/rss", Favicon: "buttondown.com"},
	{Key: "borretti", Name: "Fernando Borretti", Desc: "Programming languages and compilers", Cat: "HN Top Blogs 2025", URL: "https://borretti.me/feed.xml", Favicon: "borretti.me"},
	{Key: "wheresyoured", Name: "Where's Your Ed At", Desc: "Tech industry criticism", Cat: "HN Top Blogs 2025", URL: "https://www.wheresyoured.at/rss/", Favicon: "wheresyoured.at"},
	{Key: "jaydml", Name: "Jay Dixit", Desc: "Programming and tech", Cat: "HN Top Blogs 2025", URL: "https://jayd.ml/feed.xml", Favicon: "jayd.ml"},
	{Key: "minimaxir", Name: "Max Woolf", Desc: "Data science, AI, and Python", Cat: "HN Top Blogs 2025", URL: "https://minimaxir.com/index.xml", Favicon: "minimaxir.com"},
	{Key: "paulgraham", Name: "Paul Graham", Desc: "Startups, programming, and essays", Cat: "HN Top Blogs 2025", URL: "http://www.aaronsw.com/2002/feeds/pgessays.rss", Favicon: "paulgraham.com"},
	{Key: "filfre", Name: "The Digital Antiquarian", Desc: "History of computing and games", Cat: "HN Top Blogs 2025", URL: "https://www.filfre.net/feed/", Favicon: "filfre.net"},
	{Key: "jimnielsen", Name: "Jim Nielsen", Desc: "Web design and development", Cat: "HN Top Blogs 2025", URL: "https://blog.jim-nielsen.com/feed.xml", Favicon: "blog.jim-nielsen.com"},
	{Key: "dfarq", Name: "Dave Farquhar", Desc: "Vintage computing and IT", Cat: "HN Top Blogs 2025", URL: "https://dfarq.homeip.net/feed/", Favicon: "dfarq.homeip.net"},
	{Key: "jyndev", Name: "jyn", Desc: "Rust and compiler development", Cat: "HN Top Blogs 2025", URL: "https://jyn.dev/atom.xml", Favicon: "jyn.dev"},
	{Key: "geoffreylitt", Name: "Geoffrey Litt", Desc: "End-user programming and local-first", Cat: "HN Top Blogs 2025", URL: "https://www.geoffreylitt.com/feed.xml", Favicon: "geoffreylitt.com"},
	{Key: "dougbrown", Name: "Doug Brown", Desc: "Retro computing and hardware hacking", Cat: "HN Top Blogs 2025", URL: "https://www.downtowndougbrown.com/feed/", Favicon: "downtowndougbrown.com"},
	{Key: "brutecat", Name: "Brutecat", Desc: "Security research and exploits", Cat: "HN Top Blogs 2025", URL: "https://brutecat.com/rss.xml", Favicon: "brutecat.com"},
	{Key: "abortretryfail", Name: "Abort Retry Fail", Desc: "Computing history and retro tech", Cat: "HN Top Blogs 2025", URL: "https://www.abortretry.fail/feed", Favicon: "abortretry.fail"},
	{Key: "oldvcr", Name: "Old VCR", Desc: "Vintage computing and retrotech", Cat: "HN Top Blogs 2025", URL: "https://oldvcr.blogspot.com/feeds/posts/default", Favicon: "oldvcr.blogspot.com"},
	{Key: "bogdanthegeek", Name: "Bogdan Rosu", Desc: "Electronics and embedded systems", Cat: "HN Top Blogs 2025", URL: "https://bogdanthegeek.github.io/blog/index.xml", Favicon: "bogdanthegeek.github.io"},
	{Key: "hugotunius", Name: "Hugo Tunius", Desc: "Software engineering and compilers", Cat: "HN Top Blogs 2025", URL: "https://hugotunius.se/feed.xml", Favicon: "hugotunius.se"},
	{Key: "berthub", Name: "bert hubert", Desc: "DNS, networking, and policy", Cat: "HN Top Blogs 2025", URL: "https://berthub.eu/articles/index.xml", Favicon: "berthub.eu"},
	{Key: "chadnauseam", Name: "Chad Nauseam", Desc: "Philosophy, AI, and contrarian takes", Cat: "HN Top Blogs 2025", URL: "https://chadnauseam.com/rss.xml", Favicon: "chadnauseam.com"},
	{Key: "simoneorg", Name: "Simone", Desc: "Creative tech projects and hardware", Cat: "HN Top Blogs 2025", URL: "https://simone.org/feed/", Favicon: "simone.org"},
	{Key: "dragas", Name: "IT Notes", Desc: "Sysadmin and IT operations", Cat: "HN Top Blogs 2025", URL: "https://it-notes.dragas.net/feed/", Favicon: "it-notes.dragas.net"},
	{Key: "beej", Name: "Beej's Blog", Desc: "Network programming guides and C", Cat: "HN Top Blogs 2025", URL: "https://beej.us/blog/rss.xml", Favicon: "beej.us"},
	{Key: "heyparis", Name: "hey.paris", Desc: "Design and technology", Cat: "HN Top Blogs 2025", URL: "https://hey.paris/index.xml", Favicon: "hey.paris"},
	{Key: "danielwirtz", Name: "Daniel Wirtz", Desc: "Design, productivity, and indie dev", Cat: "HN Top Blogs 2025", URL: "https://danielwirtz.com/rss.xml", Favicon: "danielwirtz.com"},
	{Key: "matduggan", Name: "Mat Duggan", Desc: "Infrastructure and DevOps", Cat: "HN Top Blogs 2025", URL: "https://matduggan.com/rss/", Favicon: "matduggan.com"},
	{Key: "refactoringenglish", Name: "Refactoring English", Desc: "Technical writing and communication", Cat: "HN Top Blogs 2025", URL: "https://refactoringenglish.com/index.xml", Favicon: "refactoringenglish.com"},
	{Key: "worksonmymachine", Name: "Works On My Machine", Desc: "Software and engineering culture", Cat: "HN Top Blogs 2025", URL: "https://worksonmymachine.substack.com/feed", Favicon: "worksonmymachine.substack.com"},
	{Key: "philiplaine", Name: "Philip Laine", Desc: "Kubernetes and cloud native", Cat: "HN Top Blogs 2025", URL: "https://philiplaine.com/index.xml", Favicon: "philiplaine.com"},
	{Key: "steveblank", Name: "Steve Blank", Desc: "Startups and entrepreneurship", Cat: "HN Top Blogs 2025", URL: "https://steveblank.com/feed/", Favicon: "steveblank.com"},
	{Key: "bernsteinbear", Name: "Max Bernstein", Desc: "Compilers, runtimes, and PL research", Cat: "HN Top Blogs 2025", URL: "https://bernsteinbear.com/feed.xml", Favicon: "bernsteinbear.com"},
	{Key: "danieldelaney", Name: "Daniel Delaney", Desc: "Web and software engineering", Cat: "HN Top Blogs 2025", URL: "https://danieldelaney.net/feed", Favicon: "danieldelaney.net"},
	{Key: "troyhunt", Name: "Troy Hunt", Desc: "Security, HIBP, and web safety", Cat: "HN Top Blogs 2025", URL: "https://www.troyhunt.com/rss/", Favicon: "troyhunt.com"},
	{Key: "herman", Name: "Herman Martinus", Desc: "Indie dev and Bear Blog creator", Cat: "HN Top Blogs 2025", URL: "https://herman.bearblog.dev/feed/", Favicon: "herman.bearblog.dev"},
	{Key: "tomrenner", Name: "Tom Renner", Desc: "Engineering and tech", Cat: "HN Top Blogs 2025", URL: "https://tomrenner.com/index.xml", Favicon: "tomrenner.com"},
	{Key: "pixelmelt", Name: "PixelMelt", Desc: "Creative coding and projects", Cat: "HN Top Blogs 2025", URL: "https://blog.pixelmelt.dev/rss/", Favicon: "blog.pixelmelt.dev"},
	{Key: "martinalderson", Name: "Martin Alderson", Desc: "Security and tech", Cat: "HN Top Blogs 2025", URL: "https://martinalderson.com/feed.xml", Favicon: "martinalderson.com"},
	{Key: "danielhooper", Name: "Daniel Hooper", Desc: "Graphics, shaders, and creative coding", Cat: "HN Top Blogs 2025", URL: "https://danielchasehooper.com/feed.xml", Favicon: "danielchasehooper.com"},
	{Key: "sgtatham", Name: "Simon Tatham", Desc: "PuTTY author on puzzles and programming", Cat: "HN Top Blogs 2025", URL: "https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml", Favicon: "chiark.greenend.org.uk"},
	{Key: "grantslatton", Name: "Grant Slatton", Desc: "Programming and software engineering", Cat: "HN Top Blogs 2025", URL: "https://grantslatton.com/rss.xml", Favicon: "grantslatton.com"},
	{Key: "experimentalhistory", Name: "Experimental History", Desc: "Science, psychology, and culture", Cat: "HN Top Blogs 2025", URL: "https://www.experimental-history.com/feed", Favicon: "experimental-history.com"},
	{Key: "anildash", Name: "Anil Dash", Desc: "Tech culture, ethics, and the web", Cat: "HN Top Blogs 2025", URL: "https://anildash.com/feed.xml", Favicon: "anildash.com"},
	{Key: "aresluna", Name: "Marcin Wichary", Desc: "Design, keyboards, and typography", Cat: "HN Top Blogs 2025", URL: "https://aresluna.org/main.rss", Favicon: "aresluna.org"},
	{Key: "stapelberg", Name: "Michael Stapelberg", Desc: "Linux, i3wm, and infrastructure", Cat: "HN Top Blogs 2025", URL: "https://michael.stapelberg.ch/feed.xml", Favicon: "michael.stapelberg.ch"},
	{Key: "miguelgrinberg", Name: "Miguel Grinberg", Desc: "Python, Flask, and web development", Cat: "HN Top Blogs 2025", URL: "https://blog.miguelgrinberg.com/feed", Favicon: "miguelgrinberg.com"},
	{Key: "keygen", Name: "Keygen", Desc: "Software licensing and distribution", Cat: "HN Top Blogs 2025", URL: "https://keygen.sh/blog/feed.xml", Favicon: "keygen.sh"},
	{Key: "mjg59", Name: "Matthew Garrett", Desc: "Linux, firmware, and security", Cat: "HN Top Blogs 2025", URL: "https://mjg59.dreamwidth.org/data/rss", Favicon: "mjg59.dreamwidth.org"},
	{Key: "computerrip", Name: "computer.rip", Desc: "Telecom, networking, and computing history", Cat: "HN Top Blogs 2025", URL: "https://computer.rip/rss.xml", Favicon: "computer.rip"},
	{Key: "tedunangst", Name: "Ted Unangst", Desc: "OpenBSD and systems programming", Cat: "HN Top Blogs 2025", URL: "https://www.tedunangst.com/flak/rss", Favicon: "tedunangst.com"},
}
