# Keep in sync with FEED_CATALOG in js/core.js
# Only fields needed server-side: key, url, special

FEED_CATALOG = [
    # Research & Science
    {'key': 'arxiv', 'url': None, 'special': 'arxiv'},
    {'key': 'nature', 'url': 'https://www.nature.com/nature.rss'},
    {'key': 'science', 'url': 'https://www.science.org/rss/news_current.xml'},
    {'key': 'quanta', 'url': 'https://www.quantamagazine.org/feed/'},
    # Tech & News
    {'key': 'hn', 'url': None, 'special': 'hn'},
    {'key': 'verge', 'url': 'https://www.theverge.com/rss/index.xml'},
    {'key': 'arstechnica', 'url': 'https://feeds.arstechnica.com/arstechnica/index'},
    {'key': 'techcrunch', 'url': 'https://techcrunch.com/feed/'},
    {'key': 'wired', 'url': 'https://www.wired.com/feed/rss'},
    {'key': 'mittr', 'url': 'https://www.technologyreview.com/feed/'},
    # Programming
    {'key': 'lobsters', 'url': 'https://lobste.rs/rss'},
    # AI & Machine Learning
    {'key': 'gradient', 'url': 'https://thegradient.pub/rss/'},
    # Security
    {'key': 'krebs', 'url': 'https://krebsonsecurity.com/feed/'},
    # Ideas & Culture
    {'key': 'aeon', 'url': 'https://aeon.co/feed'},
    {'key': 'nautilus', 'url': 'https://nautil.us/feed/'},
    # Sports
    {'key': 'espn', 'url': 'https://www.espn.com/espn/rss/news'},
    {'key': 'theathletic', 'url': 'https://theathletic.com/feed/'},
    {'key': 'bleacherreport', 'url': 'https://bleacherreport.com/articles/feed'},
    # Prediction Markets
    {'key': 'polymarket', 'url': None, 'special': 'polymarket'},
    # Programming (additional)
    {'key': 'devto', 'url': 'https://dev.to/feed'},
    {'key': 'hackernoon', 'url': 'https://hackernoon.com/feed'},
    {'key': 'smashing', 'url': 'https://www.smashingmagazine.com/feed/'},
    # AI & Machine Learning (additional)
    {'key': 'aiweirdness', 'url': 'https://www.aiweirdness.com/rss/'},
    {'key': 'mlmastery', 'url': 'https://machinelearningmastery.com/feed/'},
    # News & World
    {'key': 'reuters', 'url': 'https://feeds.reuters.com/reuters/topNews'},
    {'key': 'bbc', 'url': 'https://feeds.bbci.co.uk/news/rss.xml'},
    {'key': 'npr', 'url': 'https://feeds.npr.org/1001/rss.xml'},
    {'key': 'apnews', 'url': 'https://rsshub.app/apnews/topics/apf-topnews'},
    # Ideas & Culture (additional)
    {'key': 'atlantic', 'url': 'https://www.theatlantic.com/feed/all/'},
    {'key': 'newyorker', 'url': 'https://www.newyorker.com/feed/everything'},
    {'key': 'brainpickings', 'url': 'https://www.themarginalian.org/feed/'},
    # Science (additional)
    {'key': 'sciamerican', 'url': 'http://rss.sciam.com/ScientificAmerican-Global'},
    {'key': 'newscientist', 'url': 'https://www.newscientist.com/section/news/feed/'},
    {'key': 'phys', 'url': 'https://phys.org/rss-feed/'},
    # Design
    {'key': 'designernews', 'url': 'https://www.designernews.co/?format=rss'},
    {'key': 'sidebar', 'url': 'https://sidebar.io/feed.xml'},
    # Finance & Economics
    {'key': 'ft', 'url': 'https://www.ft.com/rss/home'},
    {'key': 'economist', 'url': 'https://www.economist.com/latest/rss.xml'},
    {'key': 'mattstoller', 'url': 'https://www.thebignewsletter.com/feed'},
    # Space
    {'key': 'nasabreaking', 'url': 'https://www.nasa.gov/news-release/feed/'},
    {'key': 'spacenews', 'url': 'https://spacenews.com/feed/'},
    # Blogs & Newsletters
    {'key': 'acx', 'url': 'https://www.astralcodexten.com/feed'},
    {'key': 'dwarkesh', 'url': 'https://www.dwarkesh.com/feed'},
    {'key': 'geohot', 'url': 'https://geohot.github.io/blog/feed.xml'},
    {'key': 'lilianweng', 'url': 'https://lilianweng.github.io/index.xml'},
    {'key': 'colah', 'url': 'https://colah.github.io/rss.xml'},
    {'key': 'dennybritz', 'url': 'https://dennybritz.com/index.xml'},
    {'key': 'gwern', 'url': 'https://gwern.substack.com/feed'},
    {'key': 'lesswrong', 'url': 'https://www.lesswrong.com/feed.xml'},
    {'key': 'trentonbricken', 'url': 'https://www.trentonbricken.com/feed.xml'},
    {'key': 'jasonwei', 'url': 'https://www.jasonwei.net/blog?format=rss'},
    {'key': 'fanpu', 'url': 'https://fanpu.io/feed.xml'},
    {'key': 'mcyoung', 'url': 'https://mcyoung.xyz/feed.xml'},
    {'key': 'itcanthink', 'url': 'https://itcanthink.substack.com/feed'},
    {'key': 'sanderai', 'url': 'https://sander.ai/feed.xml'},
    {'key': 'gundersen', 'url': 'https://gregorygundersen.com/feed.xml'},
    {'key': 'brandinho', 'url': 'https://brandinho.github.io/feed.xml'},
    {'key': 'fabiensanglard', 'url': 'https://fabiensanglard.net/rss.xml'},
    {'key': 'andyjones', 'url': 'https://andrewcharlesjones.github.io/feed.xml'},
    {'key': 'thegeeko', 'url': 'https://thegeeko.me/rss.xml'},
    {'key': 'rohany', 'url': 'https://rohany.github.io/index.xml'},
    {'key': 'eliben', 'url': 'https://eli.thegreenplace.net/feeds/all.atom.xml'},
    {'key': 'jaredtumiel', 'url': 'https://jaredtumiel.github.io/blog/feed.xml'},
    {'key': 'paulcavallaro', 'url': 'https://paulcavallaro.com/blog/index.xml'},
    {'key': 'clashluke', 'url': 'https://clashluke.github.io/index.xml'},
    {'key': 'karpathy', 'url': 'https://karpathy.bearblog.dev/feed/'},
    {'key': 'wzml', 'url': 'https://blog.wz-ml.com/feed.xml'},
    {'key': 'simonwillison', 'url': 'https://simonwillison.net/atom/everything/'},
    {'key': 'jeffgeerling', 'url': 'https://www.jeffgeerling.com/blog.xml'},
    {'key': 'robotsinplainenglish', 'url': 'https://robotsinplainenglish.substack.com/feed'},
    {'key': 'occasionalinformationist', 'url': 'https://theoccasionalinformationist.com/feed/'},
    {'key': 'bactra', 'url': 'http://bactra.org/weblog/index.rss'},
    {'key': 'nearblog', 'url': 'https://near.blog/feed/'},
    {'key': 'moultano', 'url': 'https://moultano.wordpress.com/feed/'},
    {'key': 'convergentthinking', 'url': 'https://convergentthinking.sh/index.xml'},
    {'key': 'entropicthoughts', 'url': 'https://entropicthoughts.com/feed.xml'},
    # HN Top Blogs 2025
    {'key': 'seangoedecke', 'url': 'https://www.seangoedecke.com/rss.xml'},
    {'key': 'daringfireball', 'url': 'https://daringfireball.net/feeds/main'},
    {'key': 'ericmigi', 'url': 'https://ericmigi.com/rss.xml'},
    {'key': 'antirez', 'url': 'http://antirez.com/rss'},
    {'key': 'idiallo', 'url': 'https://idiallo.com/feed.rss'},
    {'key': 'maurycyz', 'url': 'https://maurycyz.com/index.xml'},
    {'key': 'pluralistic', 'url': 'https://pluralistic.net/feed/'},
    {'key': 'shkspr', 'url': 'https://shkspr.mobi/blog/feed/'},
    {'key': 'lcamtuf', 'url': 'https://lcamtuf.substack.com/feed'},
    {'key': 'mitchellh', 'url': 'https://mitchellh.com/feed.xml'},
    {'key': 'dynomight', 'url': 'https://dynomight.net/feed.xml'},
    {'key': 'cks', 'url': 'https://utcc.utoronto.ca/~cks/space/blog/?atom'},
    {'key': 'xeiaso', 'url': 'https://xeiaso.net/blog.rss'},
    {'key': 'oldnewthing', 'url': 'https://devblogs.microsoft.com/oldnewthing/feed'},
    {'key': 'righto', 'url': 'https://www.righto.com/feeds/posts/default'},
    {'key': 'lucumr', 'url': 'https://lucumr.pocoo.org/feed.atom'},
    {'key': 'skyfall', 'url': 'https://skyfall.dev/rss.xml'},
    {'key': 'garymarcus', 'url': 'https://garymarcus.substack.com/feed'},
    {'key': 'rachelbythebay', 'url': 'https://rachelbythebay.com/w/atom.xml'},
    {'key': 'overreacted', 'url': 'https://overreacted.io/rss.xml'},
    {'key': 'timsh', 'url': 'https://timsh.org/rss/'},
    {'key': 'johndcook', 'url': 'https://www.johndcook.com/blog/feed/'},
    {'key': 'gilesthomas', 'url': 'https://gilesthomas.com/feed/rss.xml'},
    {'key': 'matklad', 'url': 'https://matklad.github.io/feed.xml'},
    {'key': 'derekthompson', 'url': 'https://www.theatlantic.com/feed/author/derek-thompson/'},
    {'key': 'evanhahn', 'url': 'https://evanhahn.com/feed.xml'},
    {'key': 'terriblesoftware', 'url': 'https://terriblesoftware.org/feed/'},
    {'key': 'rakhim', 'url': 'https://rakhim.exotext.com/rss.xml'},
    {'key': 'joanwestenberg', 'url': 'https://joanwestenberg.com/rss'},
    {'key': 'xania', 'url': 'https://xania.org/feed'},
    {'key': 'micahflee', 'url': 'https://micahflee.com/feed/'},
    {'key': 'nesbitt', 'url': 'https://nesbitt.io/feed.xml'},
    {'key': 'constructionphysics', 'url': 'https://www.construction-physics.com/feed'},
    {'key': 'tedium', 'url': 'https://feed.tedium.co/'},
    {'key': 'susam', 'url': 'https://susam.net/feed.xml'},
    {'key': 'hillelwayne', 'url': 'https://buttondown.com/hillelwayne/rss'},
    {'key': 'borretti', 'url': 'https://borretti.me/feed.xml'},
    {'key': 'wheresyoured', 'url': 'https://www.wheresyoured.at/rss/'},
    {'key': 'jaydml', 'url': 'https://jayd.ml/feed.xml'},
    {'key': 'minimaxir', 'url': 'https://minimaxir.com/index.xml'},
    {'key': 'paulgraham', 'url': 'http://www.aaronsw.com/2002/feeds/pgessays.rss'},
    {'key': 'filfre', 'url': 'https://www.filfre.net/feed/'},
    {'key': 'jimnielsen', 'url': 'https://blog.jim-nielsen.com/feed.xml'},
    {'key': 'dfarq', 'url': 'https://dfarq.homeip.net/feed/'},
    {'key': 'jyndev', 'url': 'https://jyn.dev/atom.xml'},
    {'key': 'geoffreylitt', 'url': 'https://www.geoffreylitt.com/feed.xml'},
    {'key': 'dougbrown', 'url': 'https://www.downtowndougbrown.com/feed/'},
    {'key': 'brutecat', 'url': 'https://brutecat.com/rss.xml'},
    {'key': 'abortretryfail', 'url': 'https://www.abortretry.fail/feed'},
    {'key': 'oldvcr', 'url': 'https://oldvcr.blogspot.com/feeds/posts/default'},
    {'key': 'bogdanthegeek', 'url': 'https://bogdanthegeek.github.io/blog/index.xml'},
    {'key': 'hugotunius', 'url': 'https://hugotunius.se/feed.xml'},
    {'key': 'berthub', 'url': 'https://berthub.eu/articles/index.xml'},
    {'key': 'chadnauseam', 'url': 'https://chadnauseam.com/rss.xml'},
    {'key': 'simoneorg', 'url': 'https://simone.org/feed/'},
    {'key': 'dragas', 'url': 'https://it-notes.dragas.net/feed/'},
    {'key': 'beej', 'url': 'https://beej.us/blog/rss.xml'},
    {'key': 'heyparis', 'url': 'https://hey.paris/index.xml'},
    {'key': 'danielwirtz', 'url': 'https://danielwirtz.com/rss.xml'},
    {'key': 'matduggan', 'url': 'https://matduggan.com/rss/'},
    {'key': 'refactoringenglish', 'url': 'https://refactoringenglish.com/index.xml'},
    {'key': 'worksonmymachine', 'url': 'https://worksonmymachine.substack.com/feed'},
    {'key': 'philiplaine', 'url': 'https://philiplaine.com/index.xml'},
    {'key': 'steveblank', 'url': 'https://steveblank.com/feed/'},
    {'key': 'bernsteinbear', 'url': 'https://bernsteinbear.com/feed.xml'},
    {'key': 'danieldelaney', 'url': 'https://danieldelaney.net/feed'},
    {'key': 'troyhunt', 'url': 'https://www.troyhunt.com/rss/'},
    {'key': 'herman', 'url': 'https://herman.bearblog.dev/feed/'},
    {'key': 'tomrenner', 'url': 'https://tomrenner.com/index.xml'},
    {'key': 'pixelmelt', 'url': 'https://blog.pixelmelt.dev/rss/'},
    {'key': 'martinalderson', 'url': 'https://martinalderson.com/feed.xml'},
    {'key': 'danielhooper', 'url': 'https://danielchasehooper.com/feed.xml'},
    {'key': 'sgtatham', 'url': 'https://www.chiark.greenend.org.uk/~sgtatham/quasiblog/feed.xml'},
    {'key': 'grantslatton', 'url': 'https://grantslatton.com/rss.xml'},
    {'key': 'experimentalhistory', 'url': 'https://www.experimental-history.com/feed'},
    {'key': 'anildash', 'url': 'https://anildash.com/feed.xml'},
    {'key': 'aresluna', 'url': 'https://aresluna.org/main.rss'},
    {'key': 'stapelberg', 'url': 'https://michael.stapelberg.ch/feed.xml'},
    {'key': 'miguelgrinberg', 'url': 'https://blog.miguelgrinberg.com/feed'},
    {'key': 'keygen', 'url': 'https://keygen.sh/blog/feed.xml'},
    {'key': 'mjg59', 'url': 'https://mjg59.dreamwidth.org/data/rss'},
    {'key': 'computerrip', 'url': 'https://computer.rip/rss.xml'},
    {'key': 'tedunangst', 'url': 'https://www.tedunangst.com/flak/rss'},
    # Atom Format Feeds
    {'key': 'github', 'url': 'https://github.blog/feed/'},
    {'key': 'stackoverflow', 'url': 'https://stackoverflow.blog/feed/'},
    {'key': 'reddit-programming', 'url': 'https://www.reddit.com/r/programming/.rss'},
    {'key': 'reddit-machinelearning', 'url': 'https://www.reddit.com/r/MachineLearning/.rss'},
    {'key': 'medium-engineering', 'url': 'https://medium.engineering/feed'},
    {'key': 'chromium', 'url': 'https://blog.chromium.org/feeds/posts/default'},
    {'key': 'android-developers', 'url': 'https://android-developers.googleblog.com/feeds/posts/default'},
]

CATALOG_BY_KEY = {f['key']: f for f in FEED_CATALOG}
